# Generated by Django 4.0.6 on 2022-07-25 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_user_user_permission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_permission',
            field=models.CharField(choices=[('Not Customer', 'Not Customer'), ('Customer', 'Customer')], default='Not Customer', max_length=50, verbose_name='Права устройства'),
        ),
    ]
