# Generated by Django 4.0.6 on 2022-07-26 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_v1', '0013_remove_apartment_customer_remove_house_customer'),
        ('accounts', '0007_alter_user_apartment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='house',
        ),
        migrations.AddField(
            model_name='user',
            name='house',
            field=models.ManyToManyField(blank=True, related_name='customer_houses', to='api_v1.house', verbose_name='Дом'),
        ),
    ]
