# Generated by Django 4.0.6 on 2022-07-25 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_v1', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='house',
            name='number',
        ),
        migrations.AddField(
            model_name='house',
            name='name',
            field=models.CharField(default='', max_length=100, verbose_name='Дом'),
        ),
    ]
