# Generated by Django 4.0.6 on 2022-07-25 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_v1', '0002_remove_house_number_house_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='house',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Дом'),
        ),
    ]
