# Generated by Django 4.0.6 on 2022-07-25 08:12

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api_v1', '0004_device'),
    ]

    operations = [
        migrations.CreateModel(
            name='Meter',
            fields=[
                ('uuid', models.CharField(default=uuid.uuid4, editable=False, max_length=100000, primary_key=True, serialize=False)),
                ('serial_number', models.PositiveIntegerField(unique=True)),
                ('on_off', models.CharField(choices=[('Выкл', 'Выкл'), ('Вкл', 'Вкл')], default='Выкл', max_length=50, verbose_name='Состояние')),
                ('registration', models.DateTimeField(blank=True, null=True, verbose_name='Время регистрации')),
                ('first_testify_date', models.DateTimeField(blank=True, null=True, verbose_name='Время первого показания')),
                ('start_value', models.PositiveIntegerField()),
                ('measure', models.CharField(max_length=50)),
                ('meter_permission', models.CharField(choices=[(False, False), (True, True)], default=False, max_length=50, verbose_name='Права устройства')),
            ],
        ),
        migrations.CreateModel(
            name='Node',
            fields=[
                ('uuid', models.CharField(default=uuid.uuid4, editable=False, max_length=100000, primary_key=True, serialize=False)),
                ('geo', models.CharField(max_length=150, verbose_name='Координаты')),
                ('name', models.CharField(max_length=150, verbose_name='Имя')),
                ('description', models.CharField(blank=True, max_length=150, null=True, verbose_name='Описание')),
                ('owner', models.CharField(blank=True, max_length=100, null=True, verbose_name='Владелец')),
                ('address', models.CharField(max_length=150, verbose_name='Адрес')),
            ],
        ),
    ]
