# Generated by Django 4.0.6 on 2022-07-25 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_v1', '0007_delete_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='device_permission',
            field=models.CharField(choices=[('False', 'False'), ('True', 'True')], default='False', max_length=50, verbose_name='Права устройства'),
        ),
        migrations.AlterField(
            model_name='meter',
            name='meter_permission',
            field=models.CharField(choices=[('False', 'False'), ('True', 'True')], default='False', max_length=50, verbose_name='Права устройства'),
        ),
    ]
