# Generated by Django 4.0.6 on 2022-07-25 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_v1', '0009_apartment_customer_apartment_node_house_customer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='node',
            name='node_permission',
            field=models.CharField(choices=[('False', 'False'), ('True', 'True')], default='False', max_length=50, verbose_name='Права узла'),
        ),
    ]
