# Generated by Django 4.0.6 on 2022-07-26 03:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api_v1', '0011_apartment_device_house_device'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apartment',
            name='device',
        ),
        migrations.RemoveField(
            model_name='house',
            name='device',
        ),
        migrations.AddField(
            model_name='device',
            name='apartment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='device_apartments', to='api_v1.apartment', verbose_name='Квартира'),
        ),
        migrations.AddField(
            model_name='device',
            name='house',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='device_houses', to='api_v1.house', verbose_name='Дом'),
        ),
    ]
