# Generated by Django 4.0.6 on 2022-07-26 04:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_v1', '0012_remove_apartment_device_remove_house_device_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apartment',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='house',
            name='customer',
        ),
    ]
