# Generated by Django 4.0.6 on 2022-07-26 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_v1', '0013_remove_apartment_customer_remove_house_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='meter',
            field=models.ManyToManyField(blank=True, related_name='device_meters', to='api_v1.meter', verbose_name='Счетчик'),
        ),
    ]
